# Generated by Django 3.1.3 on 2020-11-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anikyu_api', '0002_auto_20201124_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='unwanted_animes',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='wanted_animes',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='watched_animes',
        ),
        migrations.AddField(
            model_name='user',
            name='unwanted_animes',
            field=models.ManyToManyField(related_name='unwanted_animes', to='anikyu_api.Anime'),
        ),
        migrations.AddField(
            model_name='user',
            name='wanted_animes',
            field=models.ManyToManyField(related_name='wanted_animes', to='anikyu_api.Anime'),
        ),
        migrations.AddField(
            model_name='user',
            name='watched_animes',
            field=models.ManyToManyField(related_name='watched_animes', to='anikyu_api.Anime'),
        ),
    ]
